const ROOT_FOLDER_PATH = __dirname + '/.'; //TODO-SWITCH-PROD
//const ROOT_FOLDER_PATH = __dirname + '/..'; //TODO-SWITCH-DEV
const DIST_FOLDER_PATH = ROOT_FOLDER_PATH + '/dist';
const UPLOADER_FOLDER_PATH = DIST_FOLDER_PATH + '/uploader';

module.exports = {
    ROOT_FOLDER_PATH: ROOT_FOLDER_PATH,
    DIST_FOLDER_PATH: DIST_FOLDER_PATH,
    UPLOADER_FOLDER_PATH: UPLOADER_FOLDER_PATH,
    STATUS_UPLOADED: 'UPLOADED',
    STATUS_LOADING: 'LOADING',
    STATUS_UPLOADING: 'UPLOADING',
    STATUS_EDITING: 'EDITING',
    STATUS_POSTED: 'POSTED',
    STATUS_RECORDING_COMPLETE: 'RECORDING_COMPLETE',
    STATUS_PENDING: 'PENDING',
    STATUS_RECORDING: 'RECORDING',
    STATUS_FILE_NAME: 'status.txt',
    GATEWAY_URL: 'https://match.padbol.com'
    //GATEWAY_URL: 'https://localhost'
};